In [15]:
beer_dict = {
    'American Pale Ale': 'Pale Ale',
    'American Blonde Ale': 'Pale Ale',
    'Golden Ale/Blond Ale': 'Pale Ale',
    'Bitter': 'Pale Ale',
    'Pale Ale': 'Pale Ale',
    'American Pale Ale (APA)': 'Pale Ale',
    'English Pale Ale': 'Pale Ale',
    'English Bitter': 'Pale Ale',
    'Premium Bitter/ESB': 'Pale Ale',
    'English India Pale Ale (IPA)': 'Pale Ale',
    'Extra Special / Strong Bitter (ESB)': 'Pale Ale',
    'Saison / Farmhouse Ale': 'Pale Ale',
    'English Pale Mild Ale': 'Pale Ale',
    'Saison': 'Pale Ale',
    'Belgian Pale Ale': 'Pale Ale',
    'Belgian Strong Pale Ale': 'Strong Pale Ale',
    'Tripel': 'Strong Pale Ale',
    'Abbey Tripel': 'Strong Pale Ale',
    'American IPA': 'IPA',
    'Black IPA': 'IPA',
    'India Pale Ale (IPA)': 'IPA',
    'American Double / Imperial IPA': 'IPA',
    'Imperial IPA': 'IPA',
    'New England IPA (NEIPA)': 'IPA',
    'Session IPA': 'IPA',
    'Belgian IPA': 'IPA',
    'Abbey Dubbel': 'Brown/Dark Ale',
    'Dubbel': 'Brown/Dark Ale',
    'Belgian Dark Ale': 'Brown/Dark Ale',
    'American Brown Ale': 'Brown/Dark Ale',
    'Brown Ale': 'Brown/Dark Ale',
    'English Dark Mild Ale': 'Brown/Dark Ale',
    'American Black Ale': 'Brown/Dark Ale',
    'English Brown Ale': 'Brown/Dark Ale',
    'Belgian Strong Dark Ale': 'Strong Brown/Dark Ale',
    'Abt/Quadrupel': 'Strong Brown/Dark Ale',
    'Barley Wine': 'Strong Brown/Dark Ale',
    'English Barleywine': 'Strong Brown/Dark Ale',
    'American Barleywine': 'Strong Brown/Dark Ale',
    'Quadrupel (Quad)': 'Strong Brown/Dark Ale',
    'Amber Ale': 'Amber Ale',
    'American Amber Ale': 'Amber Ale',
    'Irish Red Ale': 'Amber Ale',
    'American Amber / Red Ale': 'Amber Ale',
    'Red Ale': 'Amber Ale',
    'Belgian Ale': 'Ale',
    'Irish Ale': 'Ale',
    'Old Ale': 'Ale',
    'Mild Ale': 'Ale',
    'Traditional Ale': 'Ale',
    'Scotch Ale / Wee Heavy': 'Ale',
    'Scotch Ale': 'Ale',
    'Scottish Ale': 'Ale',
    'Belgian Strong Ale': 'Strong Ale',
    'American Strong Ale': 'Strong Ale',
    'English Strong Ale': 'Strong Ale',
    'Winter Warmer': 'Strong Ale',
    'Stout': 'Stout',
    'American Stout': 'Stout',
    'Dry Stout': 'Stout',
    'American Double / Imperial Stout': 'Stout',
    'English Stout': 'Stout',
    'Imperial Stout': 'Stout',
    'Irish Dry Stout': 'Stout',
    'Foreign / Export Stout': 'Stout',
    'Oatmeal Stout': 'Stout',
    'Russian Imperial Stout': 'Stout',
    'Milk / Sweet Stout': 'Stout',
    'Foreign Stout': 'Stout',
    'Sweet Stout': 'Stout',
    'Porter': 'Porter',
    'American Porter': 'Porter',
    'Baltic Porter': 'Porter',
    'Imperial Porter': 'Porter',
    'English Porter': 'Porter',
    'American Dark Wheat Ale': 'Wheat Beer',
    'Berliner Weissbier': 'Wheat Beer',
    'Dunkelweizen': 'Wheat Beer',
    'German Hefeweizen': 'Wheat Beer',
    'Hefeweizen': 'Wheat Beer',
    'Wheat Ale': 'Wheat Beer',
    'Weizen Bock': 'Wheat Beer',
    'Roggenbier': 'Wheat Beer',
    'Weizenbock': 'Wheat Beer',
    'Witbier': 'Wheat Beer',
    'German Kristallweizen': 'Wheat Beer',
    'Berliner Weisse': 'Wheat Beer',
    'Kristalweizen': 'Wheat Beer',
    'Wheatwine': 'Wheat Beer',
    'Dunkelweizen': 'Wheat Beer',
    'American Pale Wheat Ale': 'Wheat Beer',
    'Flanders Oud Bruin': 'Wild/Sour Beer',
    'Flanders Red Ale': 'Wild/Sour Beer',
    'Gose': 'Wild/Sour Beer',
    'Lambic - Fruit': 'Wild/Sour Beer',
    'American Wild Ale': 'Wild/Sour Beer',
    'Lambic - Unblended': 'Wild/Sour Beer',
    'Lambic Style - Faro': 'Wild/Sour Beer',
    'Lambic Style - Fruit': 'Wild/Sour Beer',
    'Lambic Style - Gueuze': 'Wild/Sour Beer',
    'Lambic Style - Unblended': 'Wild/Sour Beer',
    'Sour Red/Brown': 'Wild/Sour Beer',
    'Sour/Wild Ale': 'Wild/Sour Beer',
    'Faro': 'Wild/Sour Beer',
    'Gueuze': 'Wild/Sour Beer',
    'Grodziskie/Gose/Lichtenhainer': 'Wild/Sour Beer',
    'American Adjunct Lager': 'Pilsner & Pale Lager',
    'American Pale Lager': 'Pilsner & Pale Lager',
    'Pilsener': 'Pilsner & Pale Lager',
    'Dortmunder / Export Lager': 'Pilsner & Pale Lager',
    'European Pale Lager': 'Pilsner & Pale Lager',
    'German Pilsener': 'Pilsner & Pale Lager',
    'Pale Lager': 'Pilsner & Pale Lager',
    'Munich Helles Lager': 'Pilsner & Pale Lager',
    'Pilsener (German and Czech)': 'Pilsner & Pale Lager',
    'Czech Pilsener': 'Pilsner & Pale Lager',
    'Czech Pilsner (Světlý)': 'Pilsner & Pale Lager',
    'India Style Lager': 'Pilsner & Pale Lager',
    'Imperial Pils/Strong Pale Lager': 'Pilsner & Pale Lager',
    'Kellerbier / Zwickelbier': 'Pilsner & Pale Lager',
    'Euro Pale Lager': 'Pilsner & Pale Lager',
    'Zwickel/Keller/Landbier': 'Pilsner & Pale Lager',
    'Euro Strong Lager': 'Pilsner & Pale Lager',
    'American Double / Imperial Pilsner': 'Pilsner & Pale Lager',
    'Light Lager': 'Pilsner & Pale Lager',
    'Radler/Shandy': 'Pilsner & Pale Lager',
    'Japanese Rice Lager': 'Pilsner & Pale Lager',
    'Premium Lager': 'Pilsner & Pale Lager',
    'Dortmunder/Helles': 'Pilsner & Pale Lager',
    'Doppelbock': 'Bock',
    'Eisbock': 'Bock',
    'Heller Bock': 'Bock',
    'Maibock / Helles Bock': 'Bock',
    'Bock': 'Bock',
    'Amber Lager/Vienna': 'Dark Lager',
    'Munich Dunkel Lager': 'Dark Lager',
    'Schwarzbier': 'Dark Lager',
    'Vienna Lager': 'Dark Lager',
    'American Amber / Red Lager': 'Dark Lager',
    'Dunkel/Tmavý': 'Dark Lager',
    'Dunkler Bock': 'Dark Lager',
    'Euro Dark Lager': 'Dark Lager',
    'Schwarzbier': 'Dark Lager',
    'Polotmavý': 'Dark Lager',
    'Märzen / Oktoberfest': 'Dark Lager',
    'Oktoberfest/Märzen': 'Dark Lager',
    'Rauchbier': 'Smoked',
    'Smoked': 'Smoked',
    'Smoked Beer': 'Smoked',
    'Cream Ale': 'Hybrid Beer',
    'Kölsch': 'Hybrid Beer',
    'California Common': 'Hybrid Beer',
    'California Common / Steam Beer': 'Hybrid Beer',
    'Braggot': 'Hybrid Beer',
    'Bière de Garde': 'Hybrid Beer',
    'Black & Tan': 'Hybrid Beer',
    'Altbier': 'Hybrid Beer',
    'Rye Beer': 'Hybrid Beer',
    'Chile Beer': 'Herbs/Vegetables',
    'Cider': 'Herbs/Vegetables',
    'Fruit / Vegetable Beer': 'Herbs/Vegetables',
    'Fruit Beer': 'Herbs/Vegetables',
    'Herbed / Spiced Beer': 'Herbs/Vegetables',
    'Mead': 'Herbs/Vegetables',
    'Spice/Herb/Vegetable': 'Herbs/Vegetables',
    'Specialty Grain': 'Herbs/Vegetables',
    'Sahti': 'Herbs/Vegetables',
    'Sahti/Gotlandsdricke/Koduõlu': 'Herbs/Vegetables',
    'Scottish Gruit / Ancient Herbed Ale': 'Herbs/Vegetables',
    'Pumpkin Ale': 'Herbs/Vegetables',
    'Perry': 'Herbs/Vegetables',
    'Happoshu': 'Low Alcohol',
    'Low Alcohol': 'Low Alcohol',
    'Low Alcohol Beer': 'Low Alcohol',
    'Kvass': 'Low Alcohol',
    'American Malt Liquor': 'Cocktails',
    'Bière de Champagne / Bière Brut': 'Cocktails',
    'Malt Liquor': 'Cocktails',
    'Saké - Daiginjo': 'Cocktails',
    'Saké - Futsu-shu': 'Cocktails',
    'Saké - Genshu': 'Cocktails',
    'Saké - Ginjo': 'Cocktails',
    'Saké - Honjozo': 'Cocktails',
    'Saké - Infused': 'Cocktails',
    'Saké - Junmai': 'Cocktails',
    'Saké - Koshu': 'Cocktails',
    'Saké - Namasaké': 'Cocktails',
    'Saké - Nigori': 'Cocktails',
    'Saké - Taru': 'Cocktails',
    'Saké - Tokubetsu': 'Cocktails'
}

In [23]:
unified_users['expertise'] = (unified_users['total_nbr_ratings'] >= 3352).astype(int)
unified_users

,nbr_ratings_rb,user_id,user_name,location,nbr_ratings_ba,total_nbr_ratings,expertise
0,1890.0,175852.0,Manslow,Poland,0.0,1890.0,0
1,89.0,442761.0,MAGICuenca91,Spain,0.0,89.0,0
2,169.0,288889.0,Sibarh,Poland,0.0,169.0,0
3,3371.0,250510.0,fombe89,Spain,0.0,3371.0,1
4,13043.0,122778.0,kevnic2008,Germany,0.0,13043.0,1
...,...,...,...,...,...,...,...
220853,0.0,188321.0,Everman,"United States, California",1.0,1.0,0
220854,0.0,188322.0,Justin0001,"United States, California",1.0,1.0,0
220855,0.0,188323.0,Kyungsup,NaN,1.0,1.0,0
220856,0.0,188324.0,JoeTex,"United States, California",1.0,1.0,0
220857,0.0,188325.0,Alexmatt86,"United States, California",1.0,1.0,0

In [19]:
unified_ratings['categories'] = unified_ratings['style'].str.strip().map(beer_dict)

In [25]:
equivalent_expertise = dict(zip(unified_users['user_id'], unified_users['expertise']))
unified_ratings['expertise']=unified_ratings['user_id'].map(equivalent_expertise)
unified_ratings

,beer_name,beer_id,brewery_name,brewery_id,style,date,rating,user_id,Procedence,country_user,country_brewery,year,Season,z_score,exp_mean,diff_exp_mean,ith_rating,detrend,categories,expertise
0,Abita Andygator,3.0,Abita Brewing Company,1.0,Maibock / Helles Bock,2003-10-15 10:00:00,3.55,11266.0,BA,"United States, Illinois","United States, Louisiana",2003,Autumn,-0.201923,-0.201923,0.000000,1,-0.032678,Bock,0.0
1,Abita Andygator,3.0,Abita Brewing Company,1.0,Maibock / Helles Bock,2003-12-22 11:00:00,3.85,6816.0,BA,"United States, Massachusetts","United States, Louisiana",2003,Winter,0.228929,0.013503,0.215426,2,0.397968,Bock,0.0
2,Abita Andygator,3.0,Abita Brewing Company,1.0,Maibock / Helles Bock,2004-04-06 10:00:00,2.90,5470.0,BA,"United States, Louisiana","United States, Louisiana",2004,Spring,-1.253651,-0.408882,-0.844769,3,-1.084818,Bock,0.0
3,Abita Andygator,3.0,Abita Brewing Company,1.0,Maibock / Helles Bock,2004-04-22 10:00:00,2.39,5545.0,BA,"United States, Connecticut","United States, Louisiana",2004,Spring,-2.019939,-0.811646,-1.208293,4,-1.851312,Bock,0.0
4,Abita Andygator,3.0,Abita Brewing Company,1.0,Maibock / Helles Bock,2004-05-02 10:00:00,3.28,32532.0,BA,"United States, Texas","United States, Louisiana",2004,Spring,-0.682692,-0.785855,0.103163,5,-0.514270,Bock,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15515101,Black Sheep 54 Degrees North,536472.0,Black Sheep,48.0,Pilsener,2017-07-25 10:00:00,2.50,357380.0,RB,England,England,2017,Summer,-1.528356,-1.528356,0.000000,1,-1.528356,Pilsner & Pale Lager,0.0
15515102,Carling Black Fruits Cider,536473.0,Molson Coors UK &#40;MolsonCoors&#41;,26.0,Cider,2017-07-25 10:00:00,1.80,420333.0,RB,England,England,2017,Summer,-2.709121,-2.709121,0.000000,1,-2.709121,Herbs/Vegetables,0.0
15515103,Brockley Lager,536474.0,Brockley Brewery,16390.0,Pilsener,2017-07-03 10:00:00,3.60,85632.0,RB,England,England,2017,Summer,0.327132,0.327132,0.000000,1,0.327132,Pilsner & Pale Lager,0.0
15515104,Brockley IPA,536475.0,Brockley Brewery,16390.0,India Pale Ale (IPA),2017-07-27 10:00:00,2.80,107993.0,RB,England,England,2017,Summer,-1.022314,-1.022314,0.000000,1,-1.022314,IPA,1.0
15515105,Jama / Brewklan Kyslý Úsmev 11°,536489.0,Jama Craft Brewery,18352.0,Saison,2017-07-30 10:00:00,3.30,191020.0,RB,Slovak Republic,Slovak Republic,2017,Summer,-0.178910,-0.178910,0.000000,1,-0.178910,Pale Ale,0.0

In [122]:
def weighted_average(group):
    # Define weights based on 'expertise'
    weights = {1: 1.5, 0: 1}

    # Calculate the weighted average
    weighted_avg = (group['detrend'] * group['expertise'].map(weights)).sum() / group['expertise'].map(weights).sum()

    return pd.Series({'categories': group['categories'].iloc[0], 'country_user': group['country_user'].iloc[0], 'final_score': weighted_avg})

weighted_scores = unified_ratings.groupby(['country_user', 'categories'], as_index=False).apply(weighted_average)
weighted_scores = weighted_scores.sort_values(by=['country_user', 'final_score'],  ascending=[True, False])
weighted_scores

                 categories country_user  final_score
3     Strong Brown/Dark Ale     Abkhazia     2.512559
2                    Porter     Abkhazia     2.287375
0          Herbs/Vegetables     Abkhazia    -1.585662
4                Wheat Beer     Abkhazia    -3.644316
1      Pilsner & Pale Lager     Abkhazia    -4.083522
...                     ...          ...          ...
3428   Pilsner & Pale Lager       Zambia     2.505872
3429             Wheat Beer       Zambia     0.924626
3430              Cocktails     Zimbabwe     2.836824
3432                 Porter     Zimbabwe     0.864434
3431   Pilsner & Pale Lager     Zimbabwe    -0.724133

[3433 rows x 3 columns]